### ISSUE TITLE
Error "Cannot find module 'typescript'" when compiling from global installation

### ISSUE THREAD

**Issue by spalladino** [nomiclabs/buidler#274]
When running `buidler compile` from a global installation in the sample project with the Greeter contract, I'm getting the following error:
```
$ buidler compile --show-stack-traces
An unexpected error occurred: Cannot find module 'typescript'

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at Object.register (/home/spalladino/.nvm/versions/node/v10.13.0/lib/node_modules/ts-node/src/index.ts:206:28)
    at Object.<anonymous> (/home/spalladino/.nvm/versions/node/v10.13.0/lib/node_modules/ts-node/register/index.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
```

Note that this does not happen if I run a locally installed buidler via `npx buidler compile`.

Environment:
- Ubuntu 18.10
- Node v10.13.0
- Buidler 1.0.0-beta.7

**Comment by alcuadrado** [comment]
Thanks for reporting this! 

Would you mind sharing the output of `npm list -g --depth 0`?

**Comment by spalladino** [comment]
Here it goes!

```
/home/spalladino/.nvm/versions/node/v10.13.0/lib
├── @0x/sol-compiler@3.1.7
├── @nomiclabs/buidler@1.0.0-beta.7
├── @vue/cli@3.5.5
├── ansi-regex@2.1.1
├── babel-code-frame@6.26.0
├── babel-core@6.26.3
├── create-react-app@2.1.8
├── editions@2.1.3
├── expand-tilde@2.0.2
├── ganache-cli@6.4.3
├── global-modules@1.0.0
├── lerna@3.4.3
├── npm@6.9.0
├── repo-vision@1.2.0
├── resolver-engine@0.1.1
├── truffle@5.0.18
├── truffle-flattener@1.3.0
├── ts-node@8.0.2
├── tslint@5.13.1
├── typescript@3.3.3333
├── web3@1.0.0-beta.37
├── zos@2.3.0-rc.2
└── zos-lib@2.2.1
```

**Comment by alcuadrado** [comment]
`ts-node` is doing something odd [when requiring typescript](https://github.com/TypeStrong/ts-node/blob/master/src/index.ts#L209):

```ts
  const compiler = require.resolve(options.compiler || 'typescript', { paths: [cwd, __dirname] })
```

I'll open an issue in that project.

**Comment by alcuadrado** [comment]
That code is actually correct 😅

The problem was in version `8.02`. If you update to `8.0.3` or later it would work.

**Comment by alcuadrado** [comment]
I created #275 to track improvements to this situation. I'm closing this one.

**Comment by spalladino** [comment]
Gary is right, we need to _destroy all software_. Thanks Pato!
