### ISSUE TITLE
buidler install fails

### ISSUE THREAD

**Issue by thegostep** [nomiclabs/buidler#555]
OS: mac
Node: 10/12/14
Yarn: 1.22.4

```
[test] yarn add -D @nomiclabs/buidler                                                                        11:02:13 
yarn add v1.22.4
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning @nomiclabs/buidler > mocha > mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
[6/10] ⠂ tiny-secp256k1
[-/10] ⠂ waiting...
[-/10] ⠂ waiting...
[4/10] ⠂ keccak
error /Users/thegostep/github/test/node_modules/sha3: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/thegostep/github/test/node_modules/sha3
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.0.0 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/Users/thegostep/.nvm/versions/node/v14.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/thegostep/github/test/node_modules/sha3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/thegostep/.nvm/versions/node/v14.0.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/thegostep/Library/Caches/node-gyp/14.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/thegostep/Library/Caches/node-gyp/14.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/thegostep/.nvm/versions/node/v14.0.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/thegostep/Library/Caches/node-gyp/14.0.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/thegostep/github/test/node_modules/sha3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/thegostep/.nvm/versions/node/v14.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/Users/thegostep/.nvm/versions/node/v14.0.0/bin/node" "/Users/thegostep/.nvm/versions/node/v14.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/thegostep/github/test/node_modules/sha3
```

**Comment by fzeoli** [comment]
try following this https://buidler.dev/tutorial/setting-up-the-environment.html

**Comment by thegostep** [comment]
Had to re-install xcode: https://medium.com/flawless-app-stories/gyp-no-xcode-or-clt-version-detected-macos-catalina-anansewaa-38b536389e8d
