### ISSUE TITLE
No stack trace printed after running tests

### ISSUE THREAD

**Issue by PaulRBerg** [nomiclabs/buidler#591]
Here's my smart contract and test file:

+ [Counter.sol](https://gist.github.com/PaulRBerg/d39a2479e45e61f1afc15e229a86bb07)
+ [counter.ts](https://gist.github.com/PaulRBerg/1cb81eb3fbc4026c04abfabc84ae9c4b)

I'm getting the first wallet from waffle like this:

```ts
const [wallet] = await waffle.provider.getWallets();
```

And I intentionally made one test fail to check if the stack trace is printed in the terminal, but unfortunately it doesn't work:

```
1) should count down:
Error: VM Exception while processing transaction: revert Uint256 underflow
 at Counter.countDown (contracts/Counter.sol:25)
 at processTicksAndRejections (internal/process/task_queues.js:97:5)
 at EthModule._estimateGasAction (/Users/paulrberg/Projects/Sablier/Magellan/Protocol/node_modules/@nomiclabs/buidler/src/internal/buidler-evm/provider/modules/eth.ts:388:9)
 at BuidlerEVMProvider.send (/Users/paulrberg/Projects/Sablier/Magellan/Protocol/node_modules/@nomiclabs/buidler/src/internal/buidler-evm/provider/provider.ts:82:14)
 at WaffleMockProviderAdapter.send (/Users/paulrberg/Projects/Sablier/Magellan/Protocol/node_modules/@nomiclabs/buidler-waffle/src/waffle-provider-adapter.ts:30:20)
 at async Promise.all (index 3)
```

Possibly related: https://github.com/EthWorks/Waffle/issues/270

Stack:

+ @nomiclabs@buidler@1.3.3
+ @nomiclabs@buidler-waffle@1.3.3
+ ethereum-waffle@2.5.0

**Comment by PaulRBerg** [comment]
Silly me - the stack trace is right there, on the third line. My IDE applies a gray-ish color to all lines below the "Error" line.
