### ISSUE TITLE
Transaction reverted for an unrecognized reason. Please report this to help us improve Buidler.

### ISSUE THREAD

**Issue by minton1** [nomiclabs/buidler#632]
Buidler reports "Transaction reverted for an unrecognized reason." when a require statement is called without an explanation as the second parameter. 

Maybe the message in this case should be "Transaction reverted without a reason given." or something. 

Before:
`require(currentTime > pools[id].fullPriceLastTime);`
```
  1) Coin Contract
       Price should be fetchable, but 0 since not set.:
     Error: Transaction reverted for an unrecognized reason. Please report this to help us improve Buidler.
      at UniswapPools._priceStatus (contracts/UniswapPools.sol:245)
      at UniswapPools.getPrice (contracts/UniswapPools.sol:106)
      at processTicksAndRejections (internal/process/task_queues.js:86:5)
```
After: 
`require(currentTime > pools[id].fullPriceLastTime, "No time elapsed");`
```
  1) Coin Contract
       Price should be fetchable, but 0 since not set.:
     Error: VM Exception while processing transaction: revert No time elapsed
      at UniswapPools._priceStatus (contracts/UniswapPools.sol:245)
      at UniswapPools.getPrice (contracts/UniswapPools.sol:106)
      at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

**Comment by fvictorio** [comment]
Which version of solidity are you using?

**Comment by minton1** [comment]
this is a known issue only affecting 0.63 and later

**Comment by alcuadrado** [comment]
I'm closing this, as Buidler 1.3.6 addresses it.
