### ISSUE TITLE
I have a transaction stalled pending

### ISSUE THREAD

**Issue by vporton** [nomiclabs/buidler#686]
I have a transaction started by Buidler Deployer stalled pending and don't know what to do.

I don't know how to find its nonce. I don't know how to make it unstalled after I would find the nonce.

When I try to deploy again:

```
npx buidler deploy --network rinkeby 
All contracts have already been compiled, skipping compilation.
Extracting ABIs...
An unexpected error occurred:

TypeError: Cannot read property 'toHexString' of undefined
    at isHexable (/home/porton/Projects/bounties/cryptozon/eth/node_modules/@ethersproject/bytes/lib/index.js:8:21)
    at Object.arrayify (/home/porton/Projects/bounties/cryptozon/eth/node_modules/@ethersproject/bytes/lib/index.js:65:9)
    at Object.decode (/home/porton/Projects/bounties/cryptozon/eth/node_modules/@ethersproject/rlp/lib/index.js:115:25)
    at Object.parse (/home/porton/Projects/bounties/cryptozon/eth/node_modules/@ethersproject/transactions/lib/index.js:124:27)
    at DeploymentsManager.dealWithPendingTransactions (/home/porton/Projects/bounties/cryptozon/eth/node_modules/buidler-deploy/src/DeploymentsManager.ts:284:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at DeploymentsManager.runDeploy (/home/porton/Projects/bounties/cryptozon/eth/node_modules/buidler-deploy/src/DeploymentsManager.ts:519:9)
    at Environment._runTaskDefinition (/home/porton/Projects/bounties/cryptozon/eth/node_modules/@nomiclabs/buidler/src/internal/core/runtime-environment.ts:196:14)
    at SimpleTaskDefinition.action (/home/porton/Projects/bounties/cryptozon/eth/node_modules/buidler-deploy/src/index.ts:144:7)
    at Environment._runTaskDefinition (/home/porton/Projects/bounties/cryptozon/eth/node_modules/@nomiclabs/buidler/src/internal/core/runtime-environment.ts:196:14)
```

It is on https://github.com/vporton/cryptozon/tree/105ae3e4da93c164c86b67817793b583e9211193 sources.

**Comment by alcuadrado** [comment]
Hey Victor.

This plugin is developed by a community member and is not managed in this repository. Here's where the issue should be reported: https://github.com/wighawag/buidler-deploy
