### ISSUE TITLE
loadFixture in buidler-waffle is broken

### ISSUE THREAD

**Issue by PaulRBerg** [nomiclabs/buidler#849]
## Description
As explained on [Discord](https://imgur.com/a/QmjhBLp), the [2.1.0](https://www.npmjs.com/package/@nomiclabs/buidler-waffle/v/2.1.0) release for @nomiclabs/buidler broke the `loadFixture` function.

The root of the issue is in the [fixtures.ts](https://github.com/nomiclabs/buidler/blob/buidler-waffle-v2.1.0/packages/buidler-waffle/src/fixtures.ts#L43) file. If `overrideSigners` is not manually overridden by end-users, the default `loadFixture` function has this argument to 'undefined', as per its definition in [index.ts](https://github.com/nomiclabs/buidler/blob/buidler-waffle-v2.1.0/packages/buidler-waffle/src/index.ts#L32):

```ts
loadFixture: buidlerCreateFixtureLoader(buidlerWaffleProvider)
```

As you can see, there is no second or third argument, so `overrideSigners` ends up being assigned to 'undefined'.

## Current Workaround
Fortunately, it is possible to band-aid this bug by creating a custom fixture loader, as per the [Waffle docs](https://ethereum-waffle.readthedocs.io/en/latest/fixtures.html). Here's how I did it:

```ts
import { Fixture } from "ethereum-waffle";
import { Signer } from "@ethersproject/abstract-signer";
import { waffle } from "@nomiclabs/buidler";

const { createFixtureLoader } = waffle;

export function loadFixture(signers: Signer[]): <T>(fixture: Fixture<T>) => Promise<T> {
  return createFixtureLoader(Object.values(signers));
}
```

## Possible Solution
The definition of `loadFixture` should be changed to something like this:

```ts
loadFixture: buidlerCreateFixtureLoader(buidlerWaffleProvider, await bre.ethers.getSigners()),
```

I would have made a PR, but:

+ I'm not sure how to call `bre.ethers` from within that context
+ The function type passed on to `extendEnvironment` is non-async so `await` functions cannot be executed

**Comment by PaulRBerg** [comment]
I've also just noticed that there is another potentially linked issue with the implementation of fixtures in `buidler-waffle`.

In the [fixtures.ts](https://github.com/nomiclabs/buidler/blob/buidler-waffle-v2.1.0/packages/buidler-waffle/src/fixtures.ts) file, the types are `Signer`, but in [type-extensions.d.ts](https://github.com/nomiclabs/buidler/blob/buidler-waffle-v2.1.0/packages/buidler-waffle/src/type-extensions.d.ts) file, the types are the implicit ones provided by Waffle, i.e. `Wallet`. This means that end-users must cast the `Signer` array as a `Wallet]` array, which works in most cases, but it goes against what Richard Moore (creator of ethers.js) [recommends](https://github.com/ethers-io/ethers.js/issues/263#issuecomment-639996802) doing:

> Waffle should certainly not be using Wallet as their low-level Signer as Wallet is a fairly high-level Signer. The Signer sub-class should be what they use, since a Wallet requires a private key, which many situations do not have access to.

**Comment by paulrberg** [comment]
Hey @alcuadrado, has this been addresses in Hardhat?

**Comment by Mrtenz** [comment]
@paulrberg I was running into this issue today with Hardhat, so it seems like this is not fixed yet.

**Comment by fvictorio** [comment]
Hi, I recently was able to use `loadFixture` by just using the signers from `ethers.getSigners()` instead of the ones that `loadFixture` receives. So the workaround is to just declare your fixture without any parameters.

I'm going to leave this open because at some point we need to put some serious effort into making waffle work more seamlessly with hardhat, and this is one of the several things that should work better.

**Comment by paulrberg** [comment]
I can confirm that it works now. I am importing `waffle` directly from `hardhat` and I load my fixture via `waffle.loadFixture` directly.

Yes, increasing compatibility between Hardhat and Waffle (or even implementing some of the latter's features natively) would go a long way.

**Comment by paulrberg** [comment]
*Update*: it doesn't work. The only improvement is that the types match now. I am getting this error:

```ts
TypeError: Cannot read property '0' of undefined
      at /Users/paulrberg/projects/prb-math/test/shared/fixtures.ts:28:35
      at step (test/shared/fixtures.ts:33:23)
      at Object.next (test/shared/fixtures.ts:14:53)
      at /Users/paulrberg/projects/prb-math/test/shared/fixtures.ts:8:71
      at new Promise (<anonymous>)
      at __awaiter (test/shared/fixtures.ts:4:12)
      at unitFixturePrbMathUd60x18 (test/shared/fixtures.ts:65:12)
      at Proxy.load (node_modules/@nomiclabs/hardhat-waffle/src/fixtures.ts:32:26)
      at Context.<anonymous> (test/prbMathUd60x18/PRBMathUD60x18.ts:9:45)
      at step (test/prbMathUd60x18/PRBMathUD60x18.ts:33:23)
```

The issue is that the array of signers is empty.

**Comment by fvictorio** [comment]
> The issue is that the array of signers is empty.

Which array of signers? The one received by the `fixture`? As far as I could tell, the fixture isn't receiving anything, that's why I mentioned that you should just manually get the signers instead of using the arguments. That's it, try:

```js
async function myFixture() {
  const signers = await ethers.getSigners()
  ...
```

and use that.

**Comment by paulrberg** [comment]
> Which array of signers? The one received by the fixture?

Yes.

> that's why I mentioned that you should just manually get the signers instead of using the arguments.

Oh, I see.

**Comment by Diego-c22** [comment]
You can create different functions to call a fixture with different arguments and use that functions with loadFixture()
