### ISSUE TITLE
> RuntimeError: VM Exception while processing transaction: out of gas

### ISSUE THREAD

**Issue by shrugs** [nomiclabs/buidler#9]
Hi! I was impressed with buidler while working on a side project, so I'm experimenting with switching OpenZeppelin.

Here's my in-progress branch: https://github.com/shrugs/openzeppelin-solidity/tree/feat/buidler

I'm running our test suite (which uses a custom test script `scripts/test.sh` to set account balances very high) and running into a large suite of `out of gas` errors. I expect it's due to the change in how buidler dynamically calculates gas usage, where truffle just does the dumb "max gas" thing).

You can see a minimally reproducible case by running 

```bash
npm run test -- test/Bounty.test.js
```

```
  1) Bounty
       against secure contract
         with reward
           "before each" hook for "cannot claim reward":
     RuntimeError: VM Exception while processing transaction: out of gas
      at Function.RuntimeError.fromResults (node_modules/ganache-core/lib/utils/runtimeerror.js:74:13)
      at /Users/matt/Projects/crypto/openzeppelin-solidity/node_modules/ganache-core/lib/blockchain_double.js:539:26
      at /Users/matt/Projects/crypto/openzeppelin-solidity/node_modules/async-eventemitter/node_modules/async/internal/once.js:12:16
      at replenish (node_modules/async-eventemitter/node_modules/async/internal/eachOfLimit.js:61:25)
      at /Users/matt/Projects/crypto/openzeppelin-solidity/node_modules/async-eventemitter/node_modules/async/internal/eachOfLimit.js:71:9
      at eachLimit (node_modules/async-eventemitter/node_modules/async/eachLimit.js:43:36)
      at /Users/matt/Projects/crypto/openzeppelin-solidity/node_modules/async-eventemitter/node_modules/async/internal/doLimit.js:9:16
      at VM.AsyncEventEmitter.emit (node_modules/async-eventemitter/lib/AsyncEventEmitter.js:42:3)
      at afterBlock (node_modules/ethereumjs-vm/dist/runBlock.js:52:10)
      at /Users/matt/Projects/crypto/openzeppelin-solidity/node_modules/ethereumjs-vm/dist/runBlock.js:174:9
      at /Users/matt/Projects/crypto/openzeppelin-solidity/node_modules/ethereumjs-vm/dist/cache.js:110:7
      at /Users/matt/Projects/crypto/openzeppelin-solidity/node_modules/ethereumjs-vm/node_modules/async/dist/async.js:473:16
      at replenish (node_modules/ethereumjs-vm/node_modules/async/dist/async.js:1006:25)
      at /Users/matt/Projects/crypto/openzeppelin-solidity/node_modules/ethereumjs-vm/node_modules/async/dist/async.js:1016:9
      at eachLimit$1 (node_modules/ethereumjs-vm/node_modules/async/dist/async.js:3196:24)
      at Object.<anonymous> (node_modules/ethereumjs-vm/node_modules/async/dist/async.js:1046:16)
      at /Users/matt/Projects/crypto/openzeppelin-solidity/node_modules/ethereumjs-vm/dist/cache.js:106:11
      at /Users/matt/Projects/crypto/openzeppelin-solidity/node_modules/ethereumjs-vm/node_modules/async/dist/async.js:969:16
      at next (node_modules/ethereumjs-vm/node_modules/async/dist/async.js:5225:18)
      at /Users/matt/Projects/crypto/openzeppelin-solidity/node_modules/ethereumjs-vm/dist/cache.js:103:7
      at next (node_modules/ethereumjs-vm/node_modules/async/dist/async.js:5223:28)
      at /Users/matt/Projects/crypto/openzeppelin-solidity/node_modules/ethereumjs-vm/dist/cache.js:103:7

  2) Bounty
       against broken contract
         "before each" hook for "can claim reward":
     RuntimeError: VM Exception while processing transaction: out of gas
      at Function.RuntimeError.fromResults (node_modules/ganache-core/lib/utils/runtimeerror.js:74:13)
      at /Users/matt/Projects/crypto/openzeppelin-solidity/node_modules/ganache-core/lib/blockchain_double.js:539:26
      at /Users/matt/Projects/crypto/openzeppelin-solidity/node_modules/async-eventemitter/node_modules/async/internal/once.js:12:16
      at replenish (node_modules/async-eventemitter/node_modules/async/internal/eachOfLimit.js:61:25)
      at /Users/matt/Projects/crypto/openzeppelin-solidity/node_modules/async-eventemitter/node_modules/async/internal/eachOfLimit.js:71:9
      at eachLimit (node_modules/async-eventemitter/node_modules/async/eachLimit.js:43:36)
      at /Users/matt/Projects/crypto/openzeppelin-solidity/node_modules/async-eventemitter/node_modules/async/internal/doLimit.js:9:16
      at VM.AsyncEventEmitter.emit (node_modules/async-eventemitter/lib/AsyncEventEmitter.js:42:3)
      at afterBlock (node_modules/ethereumjs-vm/dist/runBlock.js:52:10)
      at /Users/matt/Projects/crypto/openzeppelin-solidity/node_modules/ethereumjs-vm/dist/runBlock.js:174:9
      at /Users/matt/Projects/crypto/openzeppelin-solidity/node_modules/ethereumjs-vm/dist/cache.js:110:7
      at /Users/matt/Projects/crypto/openzeppelin-solidity/node_modules/ethereumjs-vm/node_modules/async/dist/async.js:473:16
      at replenish (node_modules/ethereumjs-vm/node_modules/async/dist/async.js:1006:25)
      at /Users/matt/Projects/crypto/openzeppelin-solidity/node_modules/ethereumjs-vm/node_modules/async/dist/async.js:1016:9
      at eachLimit$1 (node_modules/ethereumjs-vm/node_modules/async/dist/async.js:3196:24)
      at Object.<anonymous> (node_modules/ethereumjs-vm/node_modules/async/dist/async.js:1046:16)
      at /Users/matt/Projects/crypto/openzeppelin-solidity/node_modules/ethereumjs-vm/dist/cache.js:106:11
      at /Users/matt/Projects/crypto/openzeppelin-solidity/node_modules/ethereumjs-vm/node_modules/async/dist/async.js:969:16
      at next (node_modules/ethereumjs-vm/node_modules/async/dist/async.js:5225:18)
      at /Users/matt/Projects/crypto/openzeppelin-solidity/node_modules/ethereumjs-vm/dist/cache.js:103:7
      at next (node_modules/ethereumjs-vm/node_modules/async/dist/async.js:5223:28)
      at /Users/matt/Projects/crypto/openzeppelin-solidity/node_modules/ethereumjs-vm/dist/cache.js:103:7
```

manually setting the gas for the failing transactions (namely https://github.com/Shrugs/zeppelin-solidity/blob/feat%2Fbuidler/test/Bounty.test.js#L34) makes that specific transaction succeed.

Cheers, this is a great project.

**Comment by shrugs** [comment]
Setting `gas` equal to `blockGasLimit` in an auto network seems to do the trick. My test network looks like

```
test: {
      provider () {
        return createAutoNetwork(this);
      },
      gas: 8000000,
      blockGasLimit: 8000000,
      accounts: [
        {
          privateKey: '0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501200',
          balance: '1000000000000000000000000',
        },
        {
          privateKey: '0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501201',
          balance: '1000000000000000000000000',
        },
        {
          privateKey: '0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501202',
          balance: '1000000000000000000000000',
        },
        {
          privateKey: '0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501203',
          balance: '1000000000000000000000000',
        },
        {
          privateKey: '0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501204',
          balance: '1000000000000000000000000',
        },
        {
          privateKey: '0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501205',
          balance: '1000000000000000000000000',
        },
        {
          privateKey: '0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501206',
          balance: '1000000000000000000000000',
        },
        {
          privateKey: '0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501207',
          balance: '1000000000000000000000000',
        },
        {
          privateKey: '0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501208',
          balance: '1000000000000000000000000',
        },
        {
          privateKey: '0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501209',
          balance: '1000000000000000000000000',
        },
      ],
    },
```

so perhaps this issue is actually within truffle somewhere, since I don't see buidler affecting the gas that's used for specific method calls (I did find the code where it estimates gas for contract deployments)

**Comment by alcuadrado** [comment]
Truffle Contracts doesn't estimate the gas before calling a function. 

I started working on this, but sometimes ganache estimates way less gas than necessary, and some tests are failing. You can take a look at it in [this branch](https://github.com/trufflesuite/truffle-contract/pull/95).

**Comment by alcuadrado** [comment]
I'm closing this issue as it's no longer relevant.

We are releasing a beta version next month that always handles gas estimation automatically.
